### ISSUE TITLE
Nginx: permissions denied

### ISSUE THREAD

**Issue by Bjornskjald** [mondediefr/docker-flarum#17]
When trying to run following the instruction in readme, I get this error:
`nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)`

**Comment by hardware** [comment]
Same as : 

https://github.com/hardware/rainloop/issues/10
https://github.com/hardware/selfoss/issues/3

This bug happens sometimes with some filesystem because of alpine's nginx package compilation process.

Try this :

```yml
environment:
  - UID=nginx
  - GID=nginx
```

Or use another [filesystem driver ](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/). Otherwise, I have no other solution.

**Comment by Bjornskjald** [comment]
It works... kind of.
Now setup returns error 500.

**Comment by hardware** [comment]
> maybe I should move this to a separate issue?

Yes, and give some logs please.

```
docker logs flarum,
docker exec -ti flarum tail -f /tmp/ngx_error.log,
docker exec -ti flarum tail -f /tmp/php_error.log
```
